# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
  schedule:
  - cron: 0 0 * * *

name: download-data-make-prediction.yaml

jobs:
  download-data-make-prediction:
  
    runs-on: ubuntu-latest
        
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
      
      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Create and populate .Renviron file
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          touch .Renviron
          echo USERNAME="$USERNAME" >> .Renviron
          echo PASSWORD="$PASSWORD" >> .Renviron

      - name: Run R process
        shell: Rscript {0}
        run: |
          pak::pkg_install("frzambra/agvAPI")
          source("R/01_data_potencial.R")
            
      - name: Render       
        run: |
          quarto render readme.qmd
          
      - name: Commit files
        run: |
          git config --local user.email "jbkunst@gmail.com"
          git config --local user.name "jbkunst"
          git add *
          git commit -am "updating data and report" --author 'Joshua Kunst <jbkunst@gmail.com>'
          git push
  
    
    